Repository mainak2003/Webapp, pull requests merged in 2022-10, with the labels that each got.

#8 Navbar made responsive and added Style.css
  index.html
  style.css
Labels: enhancement, Hacktoberfest-accepted, easy

#11 Major UI Design Improvements : Updated Looks
  about.html
  index.html
Labels: Hacktoberfest-accepted, easy

#12 (Fix) Bug: Contact Us Page & Added custom theme
  Contact.html
Labels: good first issue, Hacktoberfest-accepted

#19 Update index.html
  index.html
Labels: hacktoberfest

#24 [Modify] : Home Page Card Design
  images/2.jpg
  images/temp.md
  index.html
  styles.css
Labels: good first issue, Hacktoberfest-accepted

#26 Fix issue #25: Replaced the Old Cards Section with New Trendy Design
  index.html
  styles.css
Labels: enhancement, Hacktoberfest-accepted, resolved
